name: cache-setup
description: Prepare model caches, conditionally free space, and install Python deps without pip wheel cache.
inputs:
  hf_cache_dir:
    description: "HuggingFace cache dir (workspace-local)"
    required: false
    default: ${{ github.workspace }}/.cache/hf
  torch_cache_dir:
    description: "Torch cache dir (workspace-local)"
    required: false
    default: ${{ github.workspace }}/.cache/torch
  requirements:
    description: "Path to requirements file"
    required: false
    default: requirements.txt
  pip_no_cache:
    description: "Install pip with --no-cache-dir"
    required: false
    default: 'true'
  disk_threshold_kb:
    description: "Available-kB threshold to trigger cleanup (KB)"
    required: false
    default: 2097152  # 2GB
runs:
  using: composite
  steps:
    - name: Prepare cache dirs & env
      shell: bash
      run: |
        mkdir -p "${{ inputs.hf_cache_dir }}"
        mkdir -p "${{ inputs.torch_cache_dir }}"
        echo "HF_HOME=${{ inputs.hf_cache_dir }}" >> $GITHUB_ENV
        echo "TORCH_HOME=${{ inputs.torch_cache_dir }}" >> $GITHUB_ENV

    - name: Restore model caches (workspace-local)
      uses: actions/cache@v4
      with:
        path: |
          ${{ inputs.hf_cache_dir }}
          ${{ inputs.torch_cache_dir }}
        # Stable key so both workflows can reuse the same cache
        key: ${{ runner.os }}-model-cache-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-model-cache-

    - name: Ensure disk space (conditional cleanup)
      shell: bash
      run: |
        set -euo pipefail
        echo "Disk before cleanup:"
        df -h .
        avail_kb=$(df --output=avail . | tail -n1)
        threshold=${{ inputs.disk_threshold_kb }}
        if [ "$avail_kb" -lt "$threshold" ]; then
          echo "Low disk (<${threshold} KB) — cleanup temporary caches"
          rm -rf ~/.cache/pip/wheels || true
          rm -rf ~/.cache/pip/http || true
          # Remove non-workspace model caches (workspace caches are preserved)
          rm -rf ~/.cache/torch || true
          rm -rf ~/.cache/huggingface || true
        else
          echo "Sufficient disk — skipping cleanup"
        fi
        df -h .

    - name: Install Python dependencies (no pip cache if requested)
      shell: bash
      run: |
        python -m pip install --upgrade pip setuptools wheel
        if [ "${{ inputs.pip_no_cache }}" = "true" ]; then
          pip install --no-cache-dir -r "${{ inputs.requirements }}"
        else
          pip install -r "${{ inputs.requirements }}"
        fi
