# .github/workflows/2-process-feedback.yml

name: 2 - Process New Feedback

on:
  issues:
    types: [opened]

jobs:
  process-new-like:
    runs-on: ubuntu-latest

    # --- SECURITY FIX ---
    # This job will only run if the issue was created by the repository owner.
    if: "startsWith(github.event.issue.title, 'Like:') && github.actor == github.repository_owner"

    steps:
      - name: Checkout Repository
        # We need to checkout with a PAT to be able to push back
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.PAT }}

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install Python Dependencies
        run: pip install -r requirements.txt

      - name: Run Feedback Script
        env:
          ISSUE_TITLE: ${{ github.event.issue.title }}
        run: python scripts/feedback.py

      - name: Commit and Push Updated Taste Profile
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add liked_vectors.json
          git commit -m "feat: Update taste profile with new liked paper" || echo "No changes to commit"
          git push

      - name: Close the Issue
        uses: peter-evans/close-issue@v3
        with:
          issue-number: ${{ github.event.issue.number }}
          comment: "✅ Thank you for your feedback! This paper has been added to your taste profile."